// <auto-generated />
using System;
using Cards.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cards.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200809104752_AddSession")]
    partial class AddSession
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Cards.DataAccess.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeckName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 10000,
                            DeckName = "Sample",
                            PictureUri = "https://drive.google.com/uc?export=view&id=1X1ChJjhZkvnBGP4De8Gf5MnsHleaT6Qy"
                        },
                        new
                        {
                            Id = 1,
                            DeckName = "Deck_1",
                            PictureUri = "https://drive.google.com/uc?export=view&id=1Fhs5PgE7J77FEMl8ZJiupHkVUimUQ4P3"
                        },
                        new
                        {
                            Id = 2,
                            DeckName = "Deck_1",
                            PictureUri = "https://drive.google.com/uc?export=view&id=1B-m9CUp43S1ElqrzdnLQFR2rrg4pOzlI"
                        },
                        new
                        {
                            Id = 3,
                            DeckName = "Deck_1",
                            PictureUri = "https://drive.google.com/uc?export=view&id=1mHeIWMuxQnZ2qifSZxSAmoY3xPU8vV3s"
                        },
                        new
                        {
                            Id = 4,
                            DeckName = "Deck_1",
                            PictureUri = "https://drive.google.com/uc?export=view&id=1nt2QxOc7Sr5srHbhI1ITKVPOt3vwhYQh"
                        });
                });

            modelBuilder.Entity("Cards.DataAccess.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Cards.DataAccess.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MisterVovan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
